- name: This playbook will install nginx web servers on Ubuntu servers
  hosts: ubuntu
  vars:
    greeting_message: "Welcome to DevOps!"
  tasks:
  - name: Install nginx in ubuntu ansible node
    apt: name=nginx state=latest update_cache=yes

  - name: Create the custom web root folder
    file: path=/var/html mode=0755 state=directory

  - name: Retrieve the IP address of the ubuntu node
    shell: "hostname -i "
    register: ip

  - debug: var=ip

  - name: Customize nginx web server to use our custom folder while serving web page
    copy: src=default dest=/etc/nginx/sites-available/default

  - name: Deploy custom web page
    template: src=index.html.j2 dest=/var/html/index.html

  - name: Restart nginx web server in Ubuntu servers to apply config changes
    service: 
      name: nginx 
      state: restarted
      enabled: true

- name: This playbook will install nginx web servers on Rocky server
  hosts: rocky 
  vars:
    greeting_message: "Welcome to DevOps!"
  tasks:
  - name: Install Extra Packages for Enterprise Linux (EPEL) 
    yum: name=epel-release state=latest

  - name: Install nginx in  Rocky ansible node
    yum: name=nginx state=latest

  - name: Check if nginx server is already running
    shell: curl localhost
    register: output
    ignore_errors: yes

  - debug: var=output

  - name: Create the custom web root folder
    file: path=/var/html mode=0755 state=directory

  - name: Customize nginx web server to use our custom folder while serving web page
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf

  - name: Retrieve the IP address of the ubuntu node
    shell: "hostname -i "
    register: ip

  - name: Deploy custom web page
    template: src=index.html.j2 dest=/var/html/index.html

  - name: Stop the server if it is running already
    when: output.rc == 0 
    shell: nginx -s stop

  - name: Start nginx web server
    shell: nginx
