[all]
ubuntu1-jegan ansible_port=2001
ubuntu2-jegan ansible_port=2002
rocky1-jegan  ansible_port=2003
rocky2-jegan  ansible_port=2004

[ubuntu]
ubuntu[1:2]-jegan

[rocky]
rocky[1:2]-jegan

[linux:children]
ubuntu
rocky

[linux:vars]
ansible_user=root
ansible_host=localhost
ansible_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3

[app:children]
ubuntu
rocky

[web]
ubuntu1-jegan app_port=8080 weight=3
ubuntu2-jegan app_port=8080 weight=1
rocky1-jegan  app_port=8081 backup=True

[db]
rocky2-jegan
