- name: Customize nginx web server in Ubuntu to use our custom folder while serving web page
  copy: src=default dest=/etc/nginx/sites-available/default
  when: ansible_distribution == "Ubuntu" and ansible_os_family == "Debian"
